packages:
  - plugins/*
  - packages/*

linkWorkspacePackages: false

disallowWorkspaceCycles: true

nodeLinker: isolated

catalogs:
  dsh:
    '@deepseek-ai/cordis': '^4.0.0'

  tooling:
    typescript: '^5.7.0'
    vitest: '^3.0.0'
    tsdown: '^0.12.0'
    nx: '^20.4.0'
