/**
 * The wire contract between the host service and the browser client.
 *
 * These types are declared here, in the plugin's own source, rather than
 * imported from `@yadsh/dsh-audit-core`, for two reasons. The Remote artifacts
 * are generated by analysing this package's `src` alone, so a cross-package
 * type is invisible to the generator; and keeping the wire shape separate
 * means the artefact domain can evolve without silently changing what the
 * browser is handed.
 *
 * The shape is deliberately total: no field is optional and no method returns
 * `null`. An absent audit is `available: false` with zeroed fields, which is
 * one branch on the client instead of one per field. Two sentinels carry
 * "unknown" where a real zero would be a lie:
 *
 * - `toolCalls` / `toolErrors` are `-1` when the producer did not record them;
 * - string fields are `""` when the artefact did not carry them.
 */

/** The cheap per-session answer the badge and the tab read (SPEC §32). */
export interface AuditSummaryValue {
  /** `false` when this session has no audit at all; every other field is then zeroed. */
  available: boolean;
  auditId: string;
  sessionId: string;
  /** `excellent` | `good` | `mixed` | `poor` | `failed` | `insufficient_evidence`. */
  verdict: string;
  outcomeStatus: string;
  evidenceLevel: string;
  model: string;
  agentPreset: string;
  /** `-1` when the artefact did not record execution totals. */
  toolCalls: number;
  /** `-1` when the artefact did not record execution totals. */
  toolErrors: number;
  critical: number;
  major: number;
  minor: number;
  observation: number;
  /** Findings whose severity this build does not know. */
  other: number;
  /** `-1` when the analysis declared no readable version. */
  schemaVersion: number;
  modifiedAt: string;
}

/** The full audit, as two documents and their summary. */
export interface SessionAuditValue {
  available: boolean;
  summary: AuditSummaryValue;
  /**
   * `analysis.json` exactly as published.
   *
   * Sent as text rather than as a decoded value so the client can parse it
   * with `@yadsh/dsh-audit-core` — one parser for both sides, and an unknown
   * schema stays inspectable because the raw document crosses the wire
   * untouched.
   */
  analysisJson: string;
  /** `REPORT.md` exactly as published. */
  report: string;
}

/**
 * One registered audit that no session view can show (SPEC §2.3).
 *
 * The record behind this carries an `AuditError` whose message is written for
 * the host log and names filesystem paths, so only the stable `code` crosses
 * the wire: the browser is told *why*, never *where*.
 */
export interface UnattachedAuditValue {
  /** The audit directory's name, which is the only handle a reader has on it. */
  auditId: string;
  /** `unresolved` for an artefact no session claims, `invalid` for an unreadable one. */
  status: string;
  /** The blocking diagnostic's code, or `""` when the record carries none. */
  code: string;
  modifiedAt: string;
}

/** An empty summary, for a session with no audit. */
export function emptySummaryValue(sessionId: string): AuditSummaryValue {
  return {
    available: false,
    auditId: "",
    sessionId,
    verdict: "",
    outcomeStatus: "",
    evidenceLevel: "",
    model: "",
    agentPreset: "",
    toolCalls: -1,
    toolErrors: -1,
    critical: 0,
    major: 0,
    minor: 0,
    observation: 0,
    other: 0,
    schemaVersion: -1,
    modifiedAt: "",
  };
}

/** An empty audit, for a session with no audit. */
export function emptyAuditValue(sessionId: string): SessionAuditValue {
  return {
    available: false,
    summary: emptySummaryValue(sessionId),
    analysisJson: "",
    report: "",
  };
}
