// dsh-session-scope — client styling.
//
// Cosmetic only: `apply` appends this sheet and never fails the plugin when the
// document refuses it. The classes are the client's own (no host CSS-module
// names), so the chip and the editor keep working across DSH themes.
export const CSS = [
  ".wss-btnScope { box-sizing: border-box; height: 22px; display: inline-flex; align-items: center; gap: 4px; border: none; border-radius: 6px; background: var(--dsw-alias-bg-module-platform); color: var(--dsw-alias-label-secondary); padding: 0 8px; font: inherit; font-size: 12px; line-height: 22px; cursor: pointer; white-space: nowrap; }",
  ".wss-btnScope:hover:not(:disabled) { background: var(--dsw-alias-interactive-bg-hover); color: var(--dsw-alias-label-primary); }",
  ".wss-btnScope:disabled { cursor: default; opacity: .55; }",
  ".wss-btnScopeHero { height: 28px; min-height: 28px; border-radius: 16px; background: transparent; color: var(--dsw-alias-label-primary); font-size: 13px; line-height: 20px; font-weight: 500; }",
  ".wss-heroMount { display: contents; }",
  ".wss-heroProbe { display: none !important; }",
  ".wss-overlay { position: fixed; inset: 0; z-index: 1000; display: flex; align-items: center; justify-content: center; background: rgba(0,0,0,.45); }",
  ".wss-modal { box-sizing: border-box; width: min(560px, calc(100vw - 48px)); max-height: min(640px, calc(100vh - 96px)); display: flex; flex-direction: column; gap: 10px; border: 1px solid var(--dsw-alias-border-inverted); background: var(--dsw-specific-menu); box-shadow: var(--dsw-shadow-lv3); border-radius: 14px; padding: 14px; color: var(--dsw-alias-label-primary); }",
  ".wss-head { display: flex; align-items: center; justify-content: space-between; gap: 8px; }",
  ".wss-title { font-size: 14px; font-weight: 600; line-height: 20px; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
  ".wss-close { display: inline-flex; border: none; background: transparent; color: var(--dsw-alias-label-secondary); cursor: pointer; padding: 2px; border-radius: 6px; }",
  ".wss-close:hover { background: var(--dsw-alias-interactive-bg-hover); }",
  ".wss-caption { color: var(--dsw-alias-label-tertiary); font-size: 11px; line-height: 1.5; }",
  ".wss-modes { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 6px; }",
  ".wss-mode { border: 1px solid var(--dsw-alias-border-l2); border-radius: 8px; background: transparent; color: var(--dsw-alias-label-secondary); padding: 7px 8px; font: inherit; font-size: 12px; cursor: pointer; }",
  ".wss-mode:hover:not(:disabled) { background: var(--dsw-alias-interactive-bg-hover); }",
  ".wss-modeOn { border-color: var(--dsw-alias-state-business-primary); color: var(--dsw-alias-label-primary); background: var(--dsw-alias-bg-module-platform); }",
  ".wss-modeUnavailable { opacity: .55; }",
  ".wss-crumbs { display: flex; align-items: center; gap: 2px; flex-wrap: wrap; font-size: 12px; line-height: 18px; }",
  ".wss-crumb { border: none; background: transparent; color: var(--dsw-alias-label-secondary); cursor: pointer; padding: 1px 4px; border-radius: 6px; font: inherit; }",
  ".wss-crumb:hover { background: var(--dsw-alias-interactive-bg-hover); color: var(--dsw-alias-label-primary); }",
  ".wss-crumbSep { color: var(--dsw-alias-label-caption); }",
  ".wss-tree { display: flex; flex-direction: column; gap: 2px; overflow-y: auto; min-height: 120px; --dsh-scrollbar-thumb: var(--dsw-alias-scrollbar-bg-l2); --dsh-scrollbar-thumb-hover: var(--dsw-alias-scrollbar-hover-l2); }",
  ".wss-row { box-sizing: border-box; display: flex; align-items: center; gap: 8px; width: 100%; text-align: left; border: none; background: transparent; color: var(--dsw-alias-label-primary); border-radius: 8px; padding: 5px 8px; cursor: pointer; font: inherit; }",
  ".wss-row:hover { background: var(--dsw-alias-interactive-bg-hover); }",
  ".wss-rowName { display: inline-flex; align-items: center; gap: 6px; min-width: 0; flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
  ".wss-rowNameDim { opacity: .55; }",
  ".wss-check { flex: none; display: inline-flex; align-items: center; justify-content: center; width: 18px; height: 18px; border-radius: 5px; border: 1px solid var(--dsw-alias-border-l2); background: transparent; color: #fff; cursor: pointer; padding: 0; }",
  ".wss-check:hover:not(:disabled) { border-color: var(--dsw-alias-state-business-primary); }",
  ".wss-checkOn { background: var(--dsw-alias-state-business-primary); border-color: var(--dsw-alias-state-business-primary); }",
  ".wss-check:disabled { cursor: default; opacity: .6; }",
  ".wss-hint { color: var(--dsw-alias-label-caption); font-size: 10px; line-height: 14px; white-space: nowrap; }",
  ".wss-chevron { flex: none; display: inline-flex; color: var(--dsw-alias-label-caption); }",
  ".wss-foot { display: flex; align-items: center; gap: 8px; border-top: 1px solid var(--dsw-alias-border-l2); padding-top: 10px; }",
  ".wss-footRoots { min-width: 0; flex: 1; color: var(--dsw-alias-label-tertiary); font-size: 11px; line-height: 1.5; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
  ".wss-btn { border: none; border-radius: 8px; padding: 4px 12px; font: inherit; font-size: 12px; line-height: 20px; cursor: pointer; white-space: nowrap; }",
  ".wss-btn:disabled { opacity: .5; cursor: default; }",
  ".wss-btnGhost { background: var(--dsw-alias-interactive-bg-hover); color: var(--dsw-alias-label-primary); }",
  ".wss-btnPrimary { background: var(--dsw-alias-button-info-fill); color: #fff; }",
  ".wss-btnDanger { background: transparent; color: var(--dsw-alias-state-error-primary); }",
  ".wss-error { color: var(--dsw-alias-state-error-primary); font-size: 12px; line-height: 1.5; }",
  ".wss-busy { color: var(--dsw-alias-label-tertiary); font-size: 12px; line-height: 1.5; }",
  ".wss-empty { color: var(--dsw-alias-label-caption); font-size: 12px; line-height: 1.5; padding: 8px; }",
].join("\n");
