import { renderScalar } from "./render.js";
import type { PromptSectionDraft } from "../types.js";

/**
 * The prompt-sections side of a preset: the row that mounts the registrar, the
 * registrar module itself, and the shape of one section.
 *
 * Why a preset-local module instead of a plugin row: a preset that contributes
 * prompt text has to keep doing so when this editor is uninstalled. A row
 * naming an npm package would not — the preset would break the moment the
 * package left the deployment. A `./relative.mjs` row is the harness's own
 * mechanism for code a preset ships (the shipped presets and hand-authored
 * user presets both use it), it resolves from the preset's own directory, and
 * the module imports nothing from this plugin. The registrar is data-driven:
 * the sections themselves live in the row's `config.sections`, so the file is
 * written once, never rewritten per edit, and never has to be read back.
 *
 * Node-free on purpose: the browser half imports these constants too.
 * @module shared/prompt-sections
 */

/** Row id the generated sections row carries. */
export const SECTIONS_ROW_ID = "prompt-sections";

/** Module specifier the generated sections row names, relative to the preset. */
export const SECTIONS_MODULE_SPECIFIER = "./prompt-sections.mjs";

/** File name of the registrar inside the preset directory. */
export const SECTIONS_MODULE_FILE = "prompt-sections.mjs";

/** Config key the row's section list lives under. */
export const SECTIONS_CONFIG_KEY = "sections";

/** Section-name prefixes that belong to first-party plugins. */
export const FIRST_PARTY_NAME_HINT =
  /^(?:deployment|harness|tool|plan|web|file|skills?):/u;

/** Default limits for the sections side of one write. */
export const DEFAULT_MAX_SECTIONS = 32;
export const DEFAULT_MAX_SECTIONS_BYTES = 262144;
export const MAX_SECTION_NAME_LENGTH = 200;
export const MAX_SECTION_ORDER = 1_000_000;

/**
 * The registrar a preset ships.
 *
 * Written once per preset. It registers whatever the row lists, in the agent
 * scope the row is mounted in, which is what makes a section of this preset
 * shadow a deployment-global section of the same name — the reason a scoped
 * section exists. A malformed entry is a loud failure rather than a silently
 * missing section: the row is this editor's own output, and a hand edit that
 * breaks it should say so.
 */
export const SECTIONS_MODULE_SOURCE = `/**
 * Prompt sections of this preset.
 *
 * Generated by @yadsh/dsh-preset-persona-editor. The sections themselves live
 * in this row's \`config.sections\`: edit them in Settings → Persona, or here.
 * This file registers whatever the row lists, imports nothing from the editor,
 * and is written once — deleting it only costs the regeneration a later save
 * performs.
 */
export const name = 'preset-prompt-sections'

export const inject = ['systemPrompt']

/** Whether one entry carries a registrable section. */
function isSection(section) {
  return (
    section !== null
    && typeof section === 'object'
    && typeof section.name === 'string'
    && section.name !== ''
    && typeof section.order === 'number'
    && Number.isFinite(section.order)
    && typeof section.text === 'string'
  )
}

export function apply(ctx, config) {
  const sections = config === undefined || config === null ? [] : config.sections
  if (sections === undefined) return
  if (!Array.isArray(sections)) {
    throw new TypeError('prompt-sections: config.sections must be a list of prompt sections')
  }
  for (const section of sections) {
    if (!isSection(section)) {
      throw new TypeError('prompt-sections: malformed section ' + JSON.stringify(section))
    }
    if (section.enabled === false) continue
    ctx.effect(
      () => ctx.systemPrompt.section({
        name: section.name,
        order: section.order,
        text: section.text,
      }),
      'preset-prompt-sections ' + section.name,
    )
  }
}
`;

/**
 * Render the entries of a sections list at one indentation.
 *
 * One renderer serves both halves — the host splices this text into the
 * composition and the browser preview shows it — so what the preview claims is
 * what a save writes.
 * @param sections - the sections to render, in file order.
 * @param indent - column the `-` indicators start at.
 * @param eol - line ending to use.
 * @returns block-sequence text with no trailing line ending.
 */
export function renderSectionsList(
  sections: readonly PromptSectionDraft[],
  indent: number,
  eol: string,
): string {
  const pad = " ".repeat(indent);
  const keyPad = " ".repeat(indent + 2);
  return sections
    .map((section) =>
      [
        `${pad}- name: ${renderScalar(section.name, indent + 2, eol)}`,
        `${keyPad}order: ${String(section.order)}`,
        `${keyPad}text: ${renderScalar(section.text, indent + 2, eol)}`,
        `${keyPad}enabled: ${section.enabled ? "true" : "false"}`,
      ].join(eol),
    )
    .join(eol);
}

/**
 * Whether two section lists carry the same sections in the same order. The
 * browser half uses it to decide whether a draft is dirty; the host uses it to
 * prove an edit read back.
 * @param left - one list.
 * @param right - the other.
 * @returns true when every field of every entry matches.
 */
export function sameSections(
  left: readonly PromptSectionDraft[],
  right: readonly PromptSectionDraft[],
): boolean {
  return (
    left.length === right.length &&
    left.every((section, index) => {
      const other = right[index];
      return (
        other !== undefined &&
        other.name === section.name &&
        other.order === section.order &&
        other.text === section.text &&
        other.enabled === section.enabled
      );
    })
  );
}
